# Generated by Django 6.0.7 on 2026-08-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_team_teamshifts_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('en-us', 'English (United States)'), ('en-gb', 'English (United Kingdom)'), ('en-au', 'English (Australia)'), ('en-ca', 'English (Canada)'), ('de', 'Deutsch (German)'), ('de-formal', 'Deutsch (German (formal))'), ('ar', 'اَلْعَرَبِيَّةُ (Arabic)'), ('bg', 'Български (Bulgarian)'), ('bn', 'বাংলা (Bengali)'), ('ca', 'Català (Catalan)'), ('cs', 'Čeština (Czech)'), ('da', 'Dansk (Danish)'), ('el', 'Ελληνικά (Greek)'), ('es', 'Español (Spanish)'), ('fa-ir', 'قارسی (Persian)'), ('fi', 'Suomi (Finnish)'), ('fr', 'Français (French)'), ('hu', 'Magyar (Hungarian)'), ('hi', 'हिन्दी (Hindi)'), ('gu', 'ગુજરાતી (Gujarati)'), ('id', 'Bahasa Indonesia (Indonesian)'), ('it', 'Italiano (Italian)'), ('ja-jp', '日本語 (Japanese)'), ('ko', '한국어 (Korean)'), ('km', 'ខ្មែរ (Khmer)'), ('lv', 'Latviešu (Latvian)'), ('ms', 'Bahasa Melayu (Malay)'), ('ml', 'മലയാളം (Malayalam)'), ('mr', 'मराठी (Marathi)'), ('nb-no', 'Norsk bokmål (Norwegian Bokmål)'), ('nl', 'Nederlands (Dutch)'), ('nl-informal', 'Nederlands (Dutch (informal))'), ('pl', 'Polski (Polish)'), ('pl-informal', 'Polski (nieformalny) (Polish (informal))'), ('pt-br', 'Português brasileiro (Brazilian Portuguese)'), ('pt-pt', 'Português (Portuguese)'), ('ro', 'Română (Romanian)'), ('ru', 'Русский (Russian)'), ('si', 'සිංහල (Sinhala)'), ('sl', 'Slovenščina (Slovenian)'), ('sv', 'Svenska (Swedish)'), ('sw', 'Kiswahili (Swahili)'), ('ta', 'தமிழ் (Tamil)'), ('te', 'తెలుగు (Telugu)'), ('th', 'ไทย (Thai)'), ('tr', 'Türkçe (Turkish)'), ('uk', 'Українська (Ukrainian)'), ('ur', 'اردو (Urdu)'), ('vi', 'Tiếng Việt (Vietnamese)'), ('zh-hans', '简体中文 (Chinese Simplified)'), ('zh-hant', '繁體中文 (Chinese Traditional)')], default='en', max_length=32, verbose_name='Default language'),
        ),
        migrations.AlterField(
            model_name='team',
            name='force_hide_speaker_emails',
            field=models.BooleanField(default=False, help_text='When enabled, this team cannot see speaker email addresses in organiser views, exports, or API responses, but can still see other speaker details (unless “Always hide speaker details” is also enabled).', verbose_name='Always hide speaker emails only'),
        ),
        migrations.AlterField(
            model_name='team',
            name='force_hide_speaker_names',
            field=models.BooleanField(default=False, help_text='Normally, speaker anonymisation follows each event’s review settings. When enabled, this team <strong>always</strong> hides speaker names and details in proposal and review views, exports, and API responses — even if the event review phase would otherwise show them. Applies together with any track limits.', verbose_name='Always hide speaker details'),
        ),
        migrations.AlterField(
            model_name='team',
            name='limit_tracks',
            field=models.ManyToManyField(blank=True, help_text='Limit this team to the selected tracks. Members only see proposals, sessions, reviews, speakers, schedule data, exports, and API results for those tracks. Leave empty for access to all tracks in the team’s events. Configure tracks per event below.', to='base.track', verbose_name='Restrict access to tracks'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('en-us', 'English (United States)'), ('en-gb', 'English (United Kingdom)'), ('en-au', 'English (Australia)'), ('en-ca', 'English (Canada)'), ('de', 'Deutsch (German)'), ('de-formal', 'Deutsch (German (formal))'), ('ar', 'اَلْعَرَبِيَّةُ (Arabic)'), ('bg', 'Български (Bulgarian)'), ('bn', 'বাংলা (Bengali)'), ('ca', 'Català (Catalan)'), ('cs', 'Čeština (Czech)'), ('da', 'Dansk (Danish)'), ('el', 'Ελληνικά (Greek)'), ('es', 'Español (Spanish)'), ('fa-ir', 'قارسی (Persian)'), ('fi', 'Suomi (Finnish)'), ('fr', 'Français (French)'), ('hu', 'Magyar (Hungarian)'), ('hi', 'हिन्दी (Hindi)'), ('gu', 'ગુજરાતી (Gujarati)'), ('id', 'Bahasa Indonesia (Indonesian)'), ('it', 'Italiano (Italian)'), ('ja-jp', '日本語 (Japanese)'), ('ko', '한국어 (Korean)'), ('km', 'ខ្មែរ (Khmer)'), ('lv', 'Latviešu (Latvian)'), ('ms', 'Bahasa Melayu (Malay)'), ('ml', 'മലയാളം (Malayalam)'), ('mr', 'मराठी (Marathi)'), ('nb-no', 'Norsk bokmål (Norwegian Bokmål)'), ('nl', 'Nederlands (Dutch)'), ('nl-informal', 'Nederlands (Dutch (informal))'), ('pl', 'Polski (Polish)'), ('pl-informal', 'Polski (nieformalny) (Polish (informal))'), ('pt-br', 'Português brasileiro (Brazilian Portuguese)'), ('pt-pt', 'Português (Portuguese)'), ('ro', 'Română (Romanian)'), ('ru', 'Русский (Russian)'), ('si', 'සිංහල (Sinhala)'), ('sl', 'Slovenščina (Slovenian)'), ('sv', 'Svenska (Swedish)'), ('sw', 'Kiswahili (Swahili)'), ('ta', 'தமிழ் (Tamil)'), ('te', 'తెలుగు (Telugu)'), ('th', 'ไทย (Thai)'), ('tr', 'Türkçe (Turkish)'), ('uk', 'Українська (Ukrainian)'), ('ur', 'اردو (Urdu)'), ('vi', 'Tiếng Việt (Vietnamese)'), ('zh-hans', '简体中文 (Chinese Simplified)'), ('zh-hant', '繁體中文 (Chinese Traditional)')], default='en', max_length=50, verbose_name='Language'),
        ),
    ]
