# Generated by Django 6.0.7 on 2026-08-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_alter_locale_choices_native_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('en-us', 'English (United States)'), ('en-gb', 'English (United Kingdom)'), ('en-au', 'English (Australia)'), ('en-ca', 'English (Canada)'), ('de', 'Deutsch (German)'), ('de-formal', 'Deutsch (German (formal))'), ('ar', '(Arabic) اَلْعَرَبِيَّةُ'), ('bg', 'Български (Bulgarian)'), ('bn', 'বাংলা (Bengali)'), ('ca', 'Català (Catalan)'), ('cs', 'Čeština (Czech)'), ('da', 'Dansk (Danish)'), ('el', 'Ελληνικά (Greek)'), ('es', 'Español (Spanish)'), ('fa-ir', '(Persian) قارسی'), ('fi', 'Suomi (Finnish)'), ('fr', 'Français (French)'), ('hu', 'Magyar (Hungarian)'), ('hi', 'हिन्दी (Hindi)'), ('gu', 'ગુજરાતી (Gujarati)'), ('id', 'Bahasa Indonesia (Indonesian)'), ('it', 'Italiano (Italian)'), ('ja-jp', '日本語 (Japanese)'), ('ko', '한국어 (Korean)'), ('km', 'ខ្មែរ (Khmer)'), ('lv', 'Latviešu (Latvian)'), ('ms', 'Bahasa Melayu (Malay)'), ('ml', 'മലയാളം (Malayalam)'), ('mr', 'मराठी (Marathi)'), ('nb-no', 'Norsk bokmål (Norwegian Bokmål)'), ('nl', 'Nederlands (Dutch)'), ('nl-informal', 'Nederlands (Dutch (informal))'), ('pl', 'Polski (Polish)'), ('pl-informal', 'Polski (nieformalny) (Polish (informal))'), ('pt-br', 'Português brasileiro (Brazilian Portuguese)'), ('pt-pt', 'Português (Portuguese)'), ('ro', 'Română (Romanian)'), ('ru', 'Русский (Russian)'), ('si', 'සිංහල (Sinhala)'), ('sl', 'Slovenščina (Slovenian)'), ('sv', 'Svenska (Swedish)'), ('sw', 'Kiswahili (Swahili)'), ('ta', 'தமிழ் (Tamil)'), ('te', 'తెలుగు (Telugu)'), ('th', 'ไทย (Thai)'), ('tr', 'Türkçe (Turkish)'), ('uk', 'Українська (Ukrainian)'), ('ur', '(Urdu) اردو'), ('vi', 'Tiếng Việt (Vietnamese)'), ('zh-hans', '简体中文 (Chinese Simplified)'), ('zh-hant', '繁體中文 (Chinese Traditional)')], default='en', max_length=32, verbose_name='Default language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('en-us', 'English (United States)'), ('en-gb', 'English (United Kingdom)'), ('en-au', 'English (Australia)'), ('en-ca', 'English (Canada)'), ('de', 'Deutsch (German)'), ('de-formal', 'Deutsch (German (formal))'), ('ar', '(Arabic) اَلْعَرَبِيَّةُ'), ('bg', 'Български (Bulgarian)'), ('bn', 'বাংলা (Bengali)'), ('ca', 'Català (Catalan)'), ('cs', 'Čeština (Czech)'), ('da', 'Dansk (Danish)'), ('el', 'Ελληνικά (Greek)'), ('es', 'Español (Spanish)'), ('fa-ir', '(Persian) قارسی'), ('fi', 'Suomi (Finnish)'), ('fr', 'Français (French)'), ('hu', 'Magyar (Hungarian)'), ('hi', 'हिन्दी (Hindi)'), ('gu', 'ગુજરાતી (Gujarati)'), ('id', 'Bahasa Indonesia (Indonesian)'), ('it', 'Italiano (Italian)'), ('ja-jp', '日本語 (Japanese)'), ('ko', '한국어 (Korean)'), ('km', 'ខ្មែរ (Khmer)'), ('lv', 'Latviešu (Latvian)'), ('ms', 'Bahasa Melayu (Malay)'), ('ml', 'മലയാളം (Malayalam)'), ('mr', 'मराठी (Marathi)'), ('nb-no', 'Norsk bokmål (Norwegian Bokmål)'), ('nl', 'Nederlands (Dutch)'), ('nl-informal', 'Nederlands (Dutch (informal))'), ('pl', 'Polski (Polish)'), ('pl-informal', 'Polski (nieformalny) (Polish (informal))'), ('pt-br', 'Português brasileiro (Brazilian Portuguese)'), ('pt-pt', 'Português (Portuguese)'), ('ro', 'Română (Romanian)'), ('ru', 'Русский (Russian)'), ('si', 'සිංහල (Sinhala)'), ('sl', 'Slovenščina (Slovenian)'), ('sv', 'Svenska (Swedish)'), ('sw', 'Kiswahili (Swahili)'), ('ta', 'தமிழ் (Tamil)'), ('te', 'తెలుగు (Telugu)'), ('th', 'ไทย (Thai)'), ('tr', 'Türkçe (Turkish)'), ('uk', 'Українська (Ukrainian)'), ('ur', '(Urdu) اردو'), ('vi', 'Tiếng Việt (Vietnamese)'), ('zh-hans', '简体中文 (Chinese Simplified)'), ('zh-hant', '繁體中文 (Chinese Traditional)')], default='en', max_length=50, verbose_name='Language'),
        ),
    ]
